services:
  - type: web
    name: discord-giveaway-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: PORT
        fromService:
          type: web
          property: port